### ISSUE TITLE
KafkaConsumerPartitionLag possibly using the wrong field?

### ISSUE THREAD

**Issue by trnubo** [jirwin/burrow_exporter#26]
Hi

We have a situation where the kafka consumer was stopped for an upgrade and we expect the lag to increase while the upgrade is taking place. However the metrics reported in Prometheus didn't show the lag increasing. After looking at the burrow API and burrow_exporter it seem that burrow_exporter is reporting the lag at the last offset commit (`end.lag`) instead of the current lag (`current_lag`) of the partition.

```
$ curl -s http://burrow.service.docker:8000/v3/kafka/local/consumer/GROUP/lag  | jq '.'
{
  "error": false,
  "message": "consumer status returned",
  "status": {
    "cluster": "local",
    "group": "GROUP",
    "status": "ERR",
    "complete": 1,
    "partitions": [
      {
        "topic": "short",
        "partition": 0,
        "owner": "",
        "status": "STOP",
        "start": {
          "offset": 12490020,
          "timestamp": 1547163289948,
          "lag": 0
        },
        "end": {
          "offset": 12490085,
          "timestamp": 1547163309431,
          "lag": 0
        },
        "current_lag": 70131,
        "complete": 1
      },
...
```

The above if from the burrow V3 API and shows the `end.lag` as zero but the `current_lag` is positive.

I'm relatively new to Kafka and burrow so this may be by design but it seems to me that that current lag would be more useful than the lag at last commit.

Thanks

**Comment by xiu** [comment]
Encountered the same issue, opened #27 to fix it
