### ISSUE TITLE
support for burrow v3 api

### ISSUE THREAD

**Issue by VictorBHub** [jirwin/burrow_exporter#8]
burrow API upgraded to v3, while the client.go module reference v2 endpoints.
[new api](https://github.com/linkedin/Burrow/wiki/HTTP-Endpoint)

**Comment by cohadar** [comment]
Yeah, I also need this. I also made a pull request, but I see there is a competing one.
I don't care which one gets merged really.

**Comment by solsson** [comment]
It's quite identical :)

**Comment by elukey** [comment]
Any plans to merge this soon and release a new version/tag? We are really interested in using this tool as soon as possible :)

**Comment by elukey** [comment]
@jirwin Hi! Sorry for the extra ping but I am wondering if there are any plans to merge this new feature, it seems really nice and ready to go, but not sure if there are any blockers from your side. Thanks!

**Comment by jirwin** [comment]
Closing this now. I merged #12 a while back, and it appears to accomplish the same thing as this. Sorry for the delay.

**Comment by elukey** [comment]
@jirwin could you add a v0.0.5 tag and make a new release that we can track? Thanks in advance :)
